using VolSurfaceAnalysis
using Test
using Dates

@testset "VolSurfaceAnalysis" begin
    include("data/protocol/fixtures.jl")
    # kinds
    include("data/kinds/test_curves.jl")
    include("data/kinds/test_kinds.jl")
    # protocol
    include("data/protocol/test_library.jl")
    include("data/protocol/test_map.jl")
    include("data/protocol/test_by_selector.jl")
    include("data/protocol/test_time_cut.jl")
    include("data/protocol/test_clock.jl")
    include("data/protocol/test_lifecycle.jl")
    # providers
    include("data/providers/test_synth.jl")
    include("data/providers/test_providers.jl")
    include("data/providers/test_massive.jl")
    include("data/providers/test_parquet.jl")
    include("surfaces/test_bs.jl")
    include("surfaces/test_surface.jl")
    include("surfaces/test_surface_from.jl")
    include("ledger/fixtures.jl")
    include("ledger/test_contracts.jl")
    include("ledger/test_types.jl")
    include("ledger/test_cash.jl")
    include("ledger/test_book.jl")
    include("ledger/test_append.jl")
    include("ledger/test_round_trips.jl")
    include("policies/test_policy.jl")
    include("agents/test_agent.jl")
    include("backtest/test_execution.jl")
    include("backtest/test_engine.jl")
    include("backtest/test_settlement.jl")
    include("metrics/test_curve.jl")
    include("metrics/test_marks.jl")
    include("metrics/test_trades.jl")
    include("metrics/test_core.jl")
    include("metrics/test_optional.jl")
    include("metrics/test_dispatch.jl")
    include("experiment/test_experiment.jl")
    include("experiment/test_config.jl")
    include("experiment/test_identity.jl")
    include("persistence/test_store.jl")
    include("viz/test_spot.jl")
    include("viz/test_pnl.jl")
    include("regressions/test_review_findings.jl")
end
