using VolSurfaceAnalysis
using Test
using Dates

@testset "VolSurfaceAnalysis" begin
    include("data/test_quotes.jl")
    include("data/test_synth.jl")
    include("data/test_polygon.jl")
    include("market_data/fixtures.jl")
    include("market_data/test_kinds.jl")
    include("market_data/test_library.jl")
    include("market_data/test_providers.jl")
    include("market_data/test_map.jl")
    include("market_data/test_by_selector.jl")
    include("market_data/test_time_cut.jl")
    include("market_data/test_clock.jl")
    include("market_data/test_lifecycle.jl")
    include("market_data/test_parquet.jl")
    include("market_data/test_curves.jl")
    include("surfaces/test_bs.jl")
    include("surfaces/test_surface.jl")
    include("surfaces/test_surface_from.jl")
    include("positions/test_trade.jl")
    include("positions/test_position.jl")
    include("policies/test_policy.jl")
    include("agents/test_agent.jl")
    include("backtest/test_engine.jl")
    include("metrics/test_pnl_series.jl")
    include("metrics/test_core.jl")
    include("metrics/test_optional.jl")
    include("metrics/test_dispatch.jl")
    include("experiment/test_experiment.jl")
    include("experiment/test_config.jl")
    include("experiment/test_identity.jl")
    include("persistence/test_store.jl")
    include("viz/test_spot.jl")
    include("viz/test_pnl.jl")
end
