name = "VolSurfaceAnalysis"
uuid = "b18484be-7c68-40cd-be13-c5bda9828903"
version = "0.1.0-DEV"
authors = ["aleCombi <alecombi94@gmail.com> and contributors"]

[deps]

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
